/*
 * File: filenameCompare.c
 * Description: Comparator function for comparing filenames.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#include <string.h>

#include "pa3.h"

/*
 * Function Name: filenameCompare()
 * Prototype: int filenameCompare( const void * p1, const void * p2 );
 * Description: Comparator function to be used with qsort for sorting filenames
 *              alphabetically.  Compares the given arguments as strings, and
 *              returns an int indicating their relative order.
 * Parameters:  p1 -- Pointer to the first filename to compare
 *              p2 -- Pointer to the second filename to compare
 * Side Effects: None
 * Error Conditions: None
 * Return Value: 
 *   < 0, if p1 goes before p2
 *     0, if p1 is the same as p2
 *   > 0, if p1 goes after p2
 */
int filenameCompare( const void * p1, const void * p2 ) {
  return strncmp( *(char * const *)p1, *(char * const *)p2, MAX_PATH_LEN );
}
