/*
 * File: pa3Globals.c
 * Description: Global variables for pa3.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#include "pa3.h"
#include "pa3Strings.h"

// Used in hash()
int HashPrime = HASH_PRIME;
int HashStartVal = HASH_START_VAL;

