/*
 * File: pa3Strings.h
 * Description: Header file containing strings that are displayed to the user.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA3_STRINGS_H /* Header guard */
#define PA3_STRINGS_H

/* Usage strings */
#define STR_USAGE_LONG "\n"\
  "Usage: %s [-d dirname] [-s tableSize] [-h]\n"\
  "Popular Name Data Search.\n"\
  "  -d <dirname>   Name of the directory to find data;\n"\
  "                 Defaults to ./data if unspecified.\n"\
  "  -s <tableSize> The size of the hashtable to be used;\n"\
  "                 Must be a decimal value in the range [%d - %d).\n"\
  "                 Defaults to 421 if unspecified.\n"\
  "  -h             Print the long usage.\n"\
  "\n"

#define STR_USAGE_SHORT "\nUsage: %s [-d dirname] [-s tableSize] [-h]\n"\
                        "Try '%s -h' for more information.\n\n"

/* Error strings */
#define STR_ERR_MEM_EXCEEDED  "\n\tMemory limit exceeded.\n\n"
#define STR_ERR_EXTRA_ARGS    "\n\tExtra operand '%s'.\n"
#define STR_ERR_RANGE         "\n\t%s must be in the range [%d - %d).\n\n"
#define STR_ERR_CONVERTING    "\n\tConverting \"%s\" base \"%d\""
#define STR_ERR_NOTINT        "\n\t\"%s\" is not an integer.\n"
#define STR_ERR_SIZE          "tableSize"
#define STR_ERR_NAMEDATA      "\n\tCould not parse name data.\n\n"

/* Populating Data */
#define STR_CUR_DIR "."
#define STR_PARENT_DIR ".."
#define STR_PATH_FMT "%s/%s"

/* Graphing Strings */
#define STR_GRAPH_ROW "%5d | %s"
#define STR_GRAPH_UNRANKED ">%4d | %s"
#define STR_X_AXIS_MARKER "-"
#define STR_X_AXIS_SPACER "      "
#define STR_X_AXIS_LABEL \
  "        1   1   1   1   1   1   1   1"\
  "   1   1   1   1   1   1   1   2   2   2\n"\
  "        8   8   8   9   9   9   9   9"\
  "   9   9   9   9   9   9   9   0   0   0\n"\
  "        8   8   9   0   1   2   2   3"\
  "   4   5   6   6   7   8   9   0   0   1\n"\
  "        0   8   6   4   2   0   8   6"\
  "   4   2   0   8   6   4   2   0   8   6\n"

/* Interactive Search */
#define STR_PROMPT "Please enter a command: "
#define STR_NAME_NOT_FOUND "\nName %s not found\n\n"
#define COMMANDS {"graph", "stats", "help", NULL}
#define ERR_CMD_NOT_FOUND "\n%s is not a command.\n\n"
#define SEP " "
#define ERR_NAME_NOT_ENTERED "\nNo name entered.\n\n"
#define HELP_STR "\nCommands are:\n\t" \
        "graph\t[name]\t Display a graph showing a name's rank over time.\n\t"\
        "stats\t[name]\t List ranks by quadrennium for a name.\n\t"\
        "help \t\t Display this message.\n\n"

/* Statistics */
#define STATS_HEADER "Quadrennium  Gender  Rank  Gender  Rank\n"
#define STATS_FMT_BOTH      "%8d%9c%8d%6c%8d\n"
#define STATS_FMT_NO_FEMALE "%8d%9c%8c%6c%8d\n"
#define STATS_FMT_NO_MALE   "%8d%9c%8d%6c%8c\n"
#define STATS_FMT_NEITHER   "%8d%9c%8c%6c%8c\n"
#define F_HIGH_RANK "\n"\
  "%s as a female name was most popular %sin %d with a rank of %d\n"
#define F_NO_HIGH_RANK "\n"\
  "%s was not in the top 1000 female names from 1880 to 2016\n"
#define M_HIGH_RANK ""\
  "%s as a male name was most popular %sin %d with a rank of %d\n"
#define M_NO_HIGH_RANK ""\
  "%s was not in the top 1000 male names from 1880 to 2016\n"
#define STR_MOST_RECENT "most recently "

#endif
